Yasir's js file added
zakeer/cli-course pull request #26
Opened 2024-05-20 02:04 UTC by mdyasir1

Yasir's JS file added

2024-05-21 11:09 UTC, zakeer requested changes

2024-05-21 12:47 UTC, mdyasir1 commented
var firstname = "Yasir";
var lastname = " Mohammed";

var fullname =firstname + lastname;

var location= " Vijayawada";
var email="mdyasir4145@gmail.com";

console.log(`${fullname} from ${location}`)
console.log(`My email is ${email}`)

2024-05-22 11:26 UTC, zakeer requested changes

2024-05-22 11:26 UTC, zakeer commented on courses/javascript/task/yasir.js
> +var location= " Vijayawada";
```suggestion
var location= "Vijayawada";
```

Remove starting space

2024-05-22 11:26 UTC, zakeer commented on courses/javascript/task/yasir.js
> +console.log(`${fullname} from${location}`)
```suggestion
console.log(`${fullname} from ${location}`)
```

2024-05-22 11:26 UTC, zakeer commented on courses/javascript/task/yasir.js
> +var lastname = " Mohammed";
```suggestion
var lastname = "Mohammed";
```

2024-05-22 11:26 UTC, zakeer commented on courses/javascript/task/yasir.js
> +var fullname =firstname + lastname;
```suggestion
var fullname = `${firstname} ${lastname}`;
```

2024-05-29 11:00 UTC, merged